import './globals.css'
import { Inter } from 'next/font/google'
import '@fortawesome/fontawesome-free/css/all.css';
import MenuButton from './components/utils/menu';
import Footer from './components/utils/Footer';
import UserMenu from './components/utils/UserMenu';
import AdminMenu from './components/utils/AdminMenu';
import Provider from './Provider';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { getServerSession } from 'next-auth';
import { AuthOption } from './api/auth/[...nextauth]/route';
const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
async function  RootLayout({ children  }) {
  const session = await getServerSession(AuthOption)
return (
    <html lang="en">        
      <body className={`${inter.className} `}>
        <div className=' lg:m-8 overflow-hidden '>
          {
            session?.user ? (session.user.role = 'admin' ? (<AdminMenu/>):(<UserMenu/>)) : (<MenuButton/>)
          }
        <Provider>
        {children}
        </Provider>
        <Footer/>
      </div>
      <ToastContainer/>
        </body>
    </html>
  )
}
export default RootLayout
