import './globals.css'
import { Inter } from 'next/font/google'
import '@fortawesome/fontawesome-free/css/all.css';
import MenuButton from './components/utils/menu';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
      <div className=' lg:m-8 overflow-hidden'>
        <MenuButton/>
        {children}
      </div>
        </body>
    </html>
  )
}
